on:
  push:
    tags:
      - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r tengos-better-rolltables * -x ".github/*" ".idea/*" ".git/*" "*.iml"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          artifacts: tengos-better-rolltables.zip
          artifactContentType: application/zip

