on:
  push:
    tags:
      - '*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r tengos-better-rolltables * -x ".github/*" ".idea/*" ".git/*" "*.iml"
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files:
            tengos-better.rolltables.zip
